### ISSUE TITLE
DLL Injection method depending on Windows vesion

### ISSUE THREAD

**Issue by mfaerevaag** [xorrior/Random-CSharpTools#2]
I noticed in you DLL Injection, that you conditionally use either `NtCreateThreadEx` or `CreateRemoteThread` depending on the Windows version:

https://github.com/xorrior/Random-CSharpTools/blob/master/ReflectiveInjector/ReflectiveInjector/Injector.cs#L77-L103

Could you please elaborate on this?

**Comment by xorrior** [comment]
https://securityxploded.com/ntcreatethreadex.php
